language: php
php:
  - 5.2
before_script:
  - pear install --alldeps PHP_CodeSniffer
  - phpenv rehash
script:
  - phpcs -ns --extensions=php --report=summary --ignore=*/familyconnections/inc/thirdparty/*,*/familyconnections/inc/chat/* familyconnections/.
