language: php
php:
  - 5.2
before_script:
  - pear install --alldeps PHP_CodeSniffer
  - pear install pear.phpunit.de/phpcpd
  - phpenv rehash
script:
  - phpcs --extensions=php --ignore=*/familyconnections/inc/thirdparty/* ./
  - phpcpd ./
